services:
    db:
        restart: always
        # build:
        #     context: ./
        #     dockerfile: docker/mysql/Dockerfile
        image: mysql/mysql-server:8.0.26
        container_name: rappi-ml
        expose:
            - "3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        # command: bash -c "mysql rappiml --host 0.0.0.0 --port 3306 -p${MYSQL_ROOT_PASSWORD} -u root < /tmp/rappi-db.sql"

    ml-server:
        restart: always
        build: 
            context: ./
            dockerfile: docker/mlflow/Dockerfile
        image: rappi-mlflow
        container_name: rappi-mlflow
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        command: >
            bash -c "python ${SCRIPTS_DIR}/train.py --input_csv ${DATA_DIR}/orders.csv --output_dir ${TAKEN_MODEL_DIR}
            && mlflow models serve -m ${TAKEN_MODEL_DIR} -h 0.0.0.0"

    web-endpoint:
        restart: always
        build: 
            context: ./
            dockerfile: docker/webapp/Dockerfile
        image: rappi-endpoint
        container_name: rappi-endpoint
        expose:
            - "5001"
        networks:
            - frontend
            - backend
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        command: flask run --host 0.0.0.0 -p 5001

    nginx:
        restart: always
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: rappi-nginx
        container_name: rappi-nginx
        ports:
            - "81:80"
        networks:
            - frontend
        depends_on:
            - ml-server

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata:
